
spring.application.name=Apigateway2

server.port=9090
eureka.client.service-url.defaultZone=http://localhost:8787/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webmvc.routes[0].id=courseservice2
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://courseservice2
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/course/**

spring.cloud.gateway.server.webmvc.routes[1].id=studentservice2
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://studentservice2
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/student/**

# Actuator
management.endpoints.web.exposure.include=*
